<?php
 json_decode()//decoode an external json file
 file_get_contents()// get object from an external file
 microtime(true)//return time  1601661254.6409 0.64092700
 microtime(false)//return time 1601661254
 ucwords ('bring it');//upper case
 strtolower ('ABDULLAH');//convert string to lower case
 count($name_arry);//length
sort($name_arry);// sort accordinly
print_r ($name_arry);//print
$phrase = 'i love you';
$phrase = str_replace('love','hate',$phrase);
preg_match("/[hel]/","hello",$maches)//regex match
date( "G" )."<br/>";// get hour
date( "Y" )."<br/>";// get year
?>